bot_token                  = "xoxb-xxxxx"
verification_token         = "xxxxxx"
bot_id                     = "Uxxxxx"
channel_id                 = "Cxxxxx"
debug_channel_id           = "Cxxxxx"
github_username            = "kkishikawa"
github_token               = "xxxxxxx"
github_repository_owner    = "owner_name"
github_repository_name     = "repository_name"
github_commit_author_name  = "Kishikawa Katsumi"
github_commit_author_email = "kkishikawa@example.com"
infoplist_path             = "xxxxx/Info.plist"
